version: '3.1'
# networks:
#   frontend:
#     name: frontend_network
#     driver: bridge
#   backend:
#     name: backend_network
#     driver: bridge
services:
  jenkins:
    restart: always
    container_name: jenkins
    build:
      context: ./jenkins
      args:
        - CHANGE_SOURCE=${CHANGE_SOURCE}
        - TIMEZONE=${TIMEZONE}
        - SET_HTTP_PROXY=${SET_HTTP_PROXY}
        - SET_HTTPS_PROXY=${SET_HTTPS_PROXY}
        - SET_ALL_PROXY=${SET_ALL_PROXY}
    ports:
      - "${JENKINS_PORT}:8080"
      - "50000:50000"
    privileged: true
    volumes:
      - ${DATA_PATH_HOST}/jenkins:/var/jenkins_home
    environment:
      - TZ=${TIMEZONE}

  mysql57:
    container_name: mysql57
    restart: always
    image: mysql:5.7
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
      # - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
      # - ./conf/mysql/my.cnf:/etc/mysql/my.cnf:ro
      # # - ./mysql/:/var/lib/mysql/:rw
      # - ./log/mysql/:/var/log/mysql/:rw
      # - ./sources.list.stretch:/etc/apt/sources.list:ro
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      TZ: "${TIMEZONE}"
  redis:
    container_name: redis
    restart: always
    build: 
      context: ./redis
      args:
        - REDIS_PWD=${REDIS_PWD}
    volumes:
      - ${DATA_PATH_HOST}/redis:/data
    ports:
      - "${REDIS_PORT}:6379"
    environment:
      - TZ=${TIMEZONE}
