version: '3.5'
networks:
  lii_network:
    name: lii_network
    external: true
services:
  nginx:
    restart: always
    container_name: nginx
    build:
      context: ./nginx
      args:
        - DOCKER_UID=$DOCKER_UID
        - ACME_EMAIL=$ACME_EMAIL
        - http_proxy
        - https_proxy
    environment:
      - CERT_HOME=/root/acme_cert
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./nginx/sites:/etc/nginx/vhost
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/acme_cert:/root/acme_cert
      - ./nginx/acme-issue.sh:/usr/local/bin/acme-issue.sh
    ports:
      - 80:80
      - 443:443
      - 5080:5080
    networks:
      - lii_network