version: '3.5'
networks:
  lii_network:
    name: lii_network
    external: true
services:
  nginx:
    restart: always
    container_name: nginx
    build:
      context: ./nginx
      args:
        - DOCKER_UID=$DOCKER_UID
        - ACME_EMAIL=$ACME_EMAIL
        - http_proxy
        - https_proxy
    environment:
      - CERT_HOME=/root/acme_cert
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - ${DATA_PATH_HOST}/jenkins:/var/jenkins_home
      - ./logs/nginx:/var/log/nginx
      - ./nginx/sites:/etc/nginx/vhost
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/acme_cert:/root/acme_cert
      - ./nginx/acme-issue.sh:/usr/local/bin/acme-issue.sh
    ports:
      - 80:80
      - 443:443
      - 5080:5080
    networks:
      - lii_network
    depends_on:
      - php82
  php82:
    restart: always
    container_name: php82
    build:
      context: ./php-fpm
      dockerfile: Dockerfile.82
      args:
        - DOCKER_UID=$DOCKER_UID
    volumes:
      - ${APP_CODE_PATH_HOST}:/var/www
    networks:
      - lii_network
  horizon82:
    restart: always
    container_name: horizon82
    build:
      context: ./horizon
      dockerfile: Dockerfile.82
      args:
        - DOCKER_UID=$DOCKER_UID
    volumes:
      - ${APP_CODE_PATH_HOST}:/var/www
      - ./horizon/supervisord.d:/etc/supervisord.d
      - ./logs/supervisor/:/home/www-data/supervisor/logs
    networks:
      - lii_network
  mysql57:
    container_name: mysql57
    restart: always
    build:
      context: ./mysql
      dockerfile: Dockerfile.57
      args:
        - DOCKER_UID=$DOCKER_UID
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
      # - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
      # - ./conf/mysql/my.cnf:/etc/mysql/my.cnf:ro
      # # - ./mysql/:/var/lib/mysql/:rw
      # - ./log/mysql/:/var/log/mysql/:rw
      # - ./sources.list.stretch:/etc/apt/sources.list:ro
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    networks:
      - lii_network
  redis:
    container_name: redis
    restart: always
    build:
      context: ./redis
      args:
        - REDIS_PWD=${REDIS_PWD}
        - DOCKER_UID=$DOCKER_UID
    volumes:
      - ${DATA_PATH_HOST}/redis:/data
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - lii_network