FROM rikopudding/mysql:5.7


#####################################
# Set Timezone
#####################################
# RUN ln -snf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo Asia/Shanghai > /etc/timezone 
#     # && chown -R mysql:root /var/lib/mysql/

# COPY my.cnf /etc/mysql/conf.d/my.cnf
# RUN chmod 0444 /etc/mysql/conf.d/my.cnf
ARG DOCKER_UID
RUN docker-change-uid $DOCKER_UID



CMD ["mysqld"]

EXPOSE 3306
